### ISSUE TITLE
Suggestion for a Mathematics Questions Website

### ISSUE THREAD

**Issue by anshulshah96** [lnishan/awesome-competitive-programming#13]
https://erdos.sdslabs.co/
This website is hosted by  a student group at IIT Roorkee.
Please add this to your list ...

**Comment by lnishan** [comment]
Hello,

Thanks for the suggestion.

I had a quick look at the platform.
It is quite nice (and I applaud your group for the efforts),
but I'm slightly concerned about the fact that the user base consists of mostly students from IIT Roorkee.

Additionally, originality is also an important factor that matters to me.
I'm less experienced with Project-Euler-style questions and thus would appreciate if someone can help me verify the problems :)
