### ISSUE TITLE
Adding test cases generation framework

### ISSUE THREAD

**Issue by mamat-rahmat** [lnishan/awesome-competitive-programming#24]
Can I add [tcframe](https://github.com/fushar/tcframe) ?

> "tcframe is a C++ framework for generating test cases of competitive programming problems. This framework helps problem writers prepare test cases in a structured manner and ensures that the generated test cases are valid according to the specified constraints."

> tcframe is being heavily developed by Ashar Fuadi. It is based on a paper submitted to IOI conference in 2015: [Introducing tcframe: A Simple and Robust Test Cases Generation Framework](http://ioinformatics.org/oi/files/volume9.pdf#page=59), written by the same author.

> tcframe was mainly inspired from [testlib](https://github.com/MikeMirzayanov/testlib), written by Mike Mirzayanov et al.

**Comment by lnishan** [comment]
@mamat-rahmat 
Yes, I think so.

One question though: Do you use it personally?

**Comment by mamat-rahmat** [comment]
Yes. This framework is quite popular among competitive programming  entusiast in Indonesia.

**Comment by mamat-rahmat** [comment]
@lnishan What is the stars mean?
Is it based on contributor preferences?

**Comment by mamat-rahmat** [comment]
@lnishan Pull Request created #25 
I will change the stars if it's needed.

**Comment by lnishan** [comment]
Merged :)

**Comment by lnishan** [comment]
OHH!
and thanks :) (cannot believe I forgot to).

Really appreciated :)
