### ISSUE TITLE
Including IEEEXtreme

### ISSUE THREAD

**Issue by SangramChavan** [lnishan/awesome-competitive-programming#34]
https://github.com/IEEEXtreme all official content.
Would this contest be a good fit in this list ?

**Comment by babhishek21** [comment]
No. The competition is not open to all (it is open only to IEEE paid subscribers).

**Comment by lnishan** [comment]
I do not think the content of a contest is a fitting resource for this list.
Plus the reason stated by @babhishek21 (Thanks!).

Thanks for the suggestion though :)
