### ISSUE TITLE
A list of recommended books for math

### ISSUE THREAD

**Issue by lnishan** [lnishan/awesome-competitive-programming#4]
This issue is created to collect and discuss recommendations for books.

I think we would need 5 subjects: Discrete Mathematics, Linear Algebra, Concrete Mathematics, Probabilities and Statistics and Game Theory.

Personally I've only taken courses on Discrete Mathematics and (Elementary) Linear Algebra. Therefore, I cannot really judge the quality of the books.

Currently what I have in mind:

- [Discrete Mathematics and Its Applications](http://www.amazon.com/Discrete-Mathematics-Applications-Kenneth-Rosen/dp/0072899050), by Kenneth H. Rosen  
This one is pretty decent I think. I have this one on my shelf. The topics included are surprisingly relevant to competitive programming. There were many "ah ha" moments (ie. found something I saw in programming problems or resources) while I was studying the book.
- [Concrete Mathematics: A Foundation for Computer Science](http://www.amazon.com/Concrete-Mathematics-Foundation-Computer-Science/dp/0201558025), by Ronald L. Graham, Donald E. Knuth, Oren Patashnik  
I think it should be the one (seeing Knuth). I glanced through the table of contents once and thought it was fine. Nevertheless, I haven't read the book yet.

The ones I'm not quite sure:

- [Linear Algebra with Applications](http://www.amazon.com/Algebra-Applications-Edition-Featured-Introductory/dp/0321962214), by Steven J. Leon
- [Fundamentals of Probability, with Stochastic Processes](http://www.amazon.com/Fundamentals-Probability-Stochastic-Processes-Edition/dp/0131453408), by Saeed Ghahramani
- [The Joy of Game Theory: An Introduction to Strategic Thinking](http://www.amazon.com/Joy-Game-Theory-Introduction-Strategic/dp/1500497444/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=), by Presh Talwalkar  
This one is take from [here](http://mindyourdecisions.com/blog/2014/09/02/guide-to-game-theory-books/).  
I'm also not sure how relevant game theory is. I have seen problems, but only limited to [Sprague–Grundy theorem](https://en.wikipedia.org/wiki/Sprague–Grundy_theorem).

Extra one recommended by [演算法筆記](http://www.csie.ntnu.edu.tw/~u91029/book.html):

- [How to Solve It: A New Aspect of Mathematical Method](http://www.amazon.com/How-Solve-It-Mathematical-Princeton/dp/069111966X), by G. Polya

**Comment by imcaffrey** [comment]
:+1:
