### ISSUE TITLE
adding tourist( Gennady Korotkevich)  in Competitive programmers list

### ISSUE THREAD

**Issue by moghya** [lnishan/awesome-competitive-programming#46]

**Comment by lnishan** [comment]
Does he have a personal profile on Quora or anywhere else?

That section isn't a wall of fame, but a list of people worthy of following on Quora.

**Comment by prasadgujar** [comment]
There is Quora Thread About Tourist:
[Link](https://www.quora.com/topic/Gennady-Korotkevich-competitive-programmer)
And Facebook Page:
[Link](https://www.facebook.com/GennadyKorotkevich/)

**Comment by lnishan** [comment]
That's a Quora topic about tourist himself, not his own page.
I'm also aware of his Facebook fanpage.

I'm afraid these do not qualify as resources as they provide very little information.
