### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by underscoredam** [lnishan/awesome-competitive-programming#50]
The ["Data Structures and Algorithms - CodeChef Discuss"](https://discuss.codechef.com/questions/48877/data-structures-and-algorithms) link is broken.

**Comment by lnishan** [comment]
The link is up on my end, though CodeChef is extremely laggy (took 10 seconds to load).

It's probably just a temporary hiccup with their servers I would guess.

**Comment by lnishan** [comment]
Closing this as the link is up.
