### ISSUE TITLE
Temporarily not adding HackerEarth 

### ISSUE THREAD

**Issue by lnishan** [lnishan/awesome-competitive-programming#6]
[Tutorials from HackerEarth](https://learn.hackerearth.com/tutorials/).

The tutorials on this site are inconsistent in terms of quality with most of them being short and code-based. It feels as if they are for somebody who has learned that particular algorithm or data structure already.  
For this reason, I will not be referencing this site until some QA works have been put forth.

**Comment by babhishek21** [comment]
I feel that tutorials from HackerEarth are great resources. When you need a quick reference its right there. Moreover they have a great platform called [CodeMonk](https://www.hackerearth.com/codemonk/) which has short notes on important concepts and then a whole suite of practice questions with good editorials. (I started my ICPC prep from it) Adding it should be harmless, if not immediately beneficial.

**Comment by lnishan** [comment]
Hello.
Thanks for the comment.  
I just checked CodeMonk and the system and the attached tutorial notes look really, really decent. I'll definitely add that later.

I'm still not quite sure about the tutorials (follow [this link](https://learn.hackerearth.com/tutorials/)).
Examples:
- [Introduction To Dynamic Programming](https://learn.hackerearth.com/tutorial/dynamic-programming/95/introduction-to-dynamic-programming/). This is more like an example of DP.
- [C++ STL MAP and multiMAP](https://learn.hackerearth.com/tutorial/programming/56/c-stl-map-and-multimap/). This fails to cover functions like lower_bound and is code-based for the most part.

**Comment by lnishan** [comment]
I've added Code Monk and the Notes section on HackerEarth.

Thanks for the feedback!
