### ISSUE TITLE
TopCoder Cpp STL tutorial is not working.

### ISSUE THREAD

**Issue by 96mohitm** [lnishan/awesome-competitive-programming#60]
[Power up C++ with the Standard Template Library - Topcoder: Part 1](https://www.topcoder.com/community/data-science/data-science-tutorials/power-up-c-with-the-standard-template-library-part-1/), [Part 2
](https://www.topcoder.com/community/data-science/data-science-tutorials/power-up-c-with-the-standard-template-library-part-2/)
In the C/C++ section, these links are invalid.
Actually the Topcoder Data Science Tutorials Page is Under Construction.

**Comment by lnishan** [comment]
Thanks for reporting it.
I'll keep this in check.

**Comment by 96mohitm** [comment]
You're Welcome. :)

**Comment by HabiburRahmanShamim** [comment]
thanks for this (y)

**Comment by maximumevilcoverage** [comment]
They can be accessed via archive.org.

**Comment by lnishan** [comment]
The links appear to be back up!
